testserver/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from testserver.core.urls import urlpatterns as core_patterns


admin.autodiscover()
admin.site.login = login_required(admin.site.login)

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += core_patterns

testserver/core/models.py
from datetime import datetime
from itertools import chain
from itertools import product
from os import chdir
from os import listdir
from os.path import join
from time import sleep
from xml.etree import ElementTree

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db import transaction
from django.utils import timezone

from testserver.core.exceptions import SimulationRaceConditionException
from testserver.core.utils import parse_result
from testserver.core.utils import run_simulation
from testserver.core import constants


class File(models.Model):
    name = models.CharField(max_length=200, default='RobotPlayer.java', db_index=True)
    content = models.TextField()

    robot = models.ForeignKey('Robot')

    def __unicode__(self):
        return '%s [%s]' % (self.name, self.robot.line.name)


    def save(self, *args, **kwargs):

        if not self.name.endswith('.java'):
            self.name += '.java'

        super(File, self).save(*args, **kwargs)


class MapManager(models.Manager):

    def initialize(self):
        files = listdir(join(settings.BATTLECODE_ROOT, 'maps'))
        maps = []

        for filename in files:
            tree = ElementTree.parse(join(settings.BATTLECODE_ROOT, 'maps', filename))
            root = tree.getroot()

            height, width = root.attrib['height'], root.attrib['width']

            size = (float(height) * float(width)) ** 0.5
            maps.append(Map(name=filename, size=size))
        
        self.bulk_create(maps)


class Map(models.Model):
    name = models.CharField(max_length=100, unique=True)
    size = models.IntegerField(default=35, db_index=True)

    objects = MapManager()

    class Meta:
        ordering = ['name']


    def __unicode__(self):
        return self.name


class Robot(models.Model):
    active = models.BooleanField(default=True, db_index=True)
    create_time = models.DateTimeField(auto_now_add=True, db_index=True)
    creator = models.ForeignKey(User)
    line = models.ForeignKey('RobotLine')
    line_num = models.IntegerField(null=True, db_index=True)
    name = models.CharField(max_length=100, blank=True)

    simulated_opponents = models.ManyToManyField('Robot')

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):

        super(Robot, self).save(*args, **kwargs)

        if not self.line_num:
            # TODO: binary search?  Linear search time may be dwarfed by database transaction time though.
            for idx, robot in enumerate(Robot.objects.filter(line=self.line).order_by('create_time')):
                self.line_num = idx + 1
            self.name = '%s_%d' % (self.line.name, self.line_num)
            super(Robot, self).save(*args, **kwargs)  # so simulate only gets called once
            self.simulate()


    def get_predecessor(self):
        potential = Robot.objects.filter(line=self.line, line_num__lt=self.line_num, active=True).order_by('-create_time')[:1]
        try:
            return potential[0]
        except IndexError:
            return None

    
    def get_successor(self):
        potential = Robot.objects.filter(line=self.line, line_num__gt=self.line_num, active=True).order_by('create_time')[:1]
        try:
            return potential[0]
        except IndexError:
            return None


    def get_worthy_opponents(self):
        '''
        Returns a generator of worthy opponents
        '''
        predecessor = self.get_predecessor()
        if predecessor:
            yield predecessor
        for robot in Robot.objects.exclude(line__name=self.line.name).filter(active=True):
            yield robot
        yield None


    def simulate(self):
        for opponent in self.get_worthy_opponents():
            Simulation.objects.create_simulations(self, opponent)


class RobotLine(models.Model):
    name = models.CharField(max_length=100, unique=True)
    alive = models.BooleanField(default=True, db_index=True)

    def __unicode__(self):
        return self.name


class SimulationManager(models.Manager):

    def create_simulations(self, robot_a, robot_b):
        simulations = [Simulation(robot_a=robot_a, robot_b=robot_b, map_file=map_file)
                       for map_file in Map.objects.all()]
        self.bulk_create(simulations)

        if robot_b:
            robot_a.simulated_opponents.add(robot_b)
            robot_a.save()
            robot_b.simulated_opponents.add(robot_a)
            robot_b.save()


    def get_results(self, robot_a, robot_b, since=None):
        '''
        Returns three lists: simulations it won on, lost on, tied on
        Should only take in two different robots
        '''
        if robot_b:
            assert robot_a.pk > robot_b.pk

        results = [[], [], []]
        mapping = {
            constants.RESULT.ROBOT_A: 0,
            constants.RESULT.ROBOT_B: 1,
            constants.RESULT.TIE: 2,
        }
        query_kwargs = {
            'robot_a': robot_a,
            'robot_b': robot_b,
            'status': constants.STATUS.CLOSED,
        }
        if since:
            query_kwargs['finish_time__gte'] = since

        for simulation in self.select_related().filter(**query_kwargs):
            results[mapping[simulation.winner]].append(simulation)
        return results
    

    @transaction.atomic
    def get_next_simulation(self, retry=False):
        if retry:
            potential = self.select_for_update().filter(status__in=(constants.STATUS.FAILED, constants.STATUS.OPEN)).order_by('-priority')[:1]
        else:
            potential = self.select_for_update().filter(status=constants.STATUS.OPEN).order_by('-priority')[:1]
        try:
            simulation = potential[0]
            simulation.status = constants.STATUS.PENDING
            simulation.save()
            return simulation
        except IndexError:
            return None
 

class Simulation(models.Model):
    '''
    Class for running simulations.  Robot_a should be the new robot, and robot_b should be an existing one.
    Robot_a should have a higher id than robot_b.
    '''

    robot_a = models.ForeignKey('Robot', related_name='simulation_a')
    robot_b = models.ForeignKey('Robot', related_name='simulation_b', null=True, blank=True)
    map_file = models.ForeignKey('Map')

    priority = models.FloatField(default=0)
    result = models.TextField(null=True, blank=True)
    error = models.TextField(null=True, blank=True)

    status = models.CharField(max_length=1,
                              choices=constants.STATUS_CHOICES,
                              default=constants.STATUS.OPEN,)
    winner = models.CharField(max_length=1,
                              choices=constants.RESULT_CHOICES,
                              null=True, blank=True)
    tie = models.NullBooleanField(default=None, db_index=True)
    rounds = models.IntegerField(null=True, blank=True)

    create_time = models.DateTimeField(auto_now_add=True, db_index=True)
    finish_time = models.DateTimeField(null=True, blank=True, db_index=True)

    name = models.CharField(max_length=200)

    objects = SimulationManager()


    class Meta:
        ordering = ['map_file__name']


    def __init__(self, *args, **kwargs):
        super(Simulation, self).__init__(*args, **kwargs)

        if not self.priority:
            self.priority = self.calculate_priority()
        if not self.name:
            self.name = '%s vs %s on %s' % (self.robot_a,
                                            self.robot_b or constants.DEFAULT_AI,
                                            self.map_file.name)
    

    def __unicode__(self):
        return self.name
    

    def calculate_priority(self):
        if not self.robot_b:
            prior = 0.3
        elif self.robot_a.line == self.robot_b.line:  # same line
            prior = 0.5
        else:
            prior = 0.4
            # the below is pretty slow; used only for prioritizing the order of tests
            '''
            prior_results = []
            ancestors = Robot.objects.filter(line=self.robot_a.line).exclude(pk=self.robot_a.pk).order_by('line_num')
            for ancestor in ancestors:
                try:
                    simulations = Simulation.objects.filter(robot_a=ancestor, robot_b=self.robot_b,
                                                            status=constants.STATUS.CLOSED)
                except Simulation.DoesNotExist:
                    simulations = Simulation.objects.filter(robot_a=self.robot_b, robot_b=ancestor,
                                                            status=constants.STATUS.CLOSED)
                
                for simulation in simulations:
                    if simulation.result == 'T':
                        prior_results.append(0.5)
                    elif ((simulation.robot_a == ancestor and simulation.result == 'A')
                            or (simulation.robot_b == ancestor and simulation.result == 'B')):
                        prior_results.append(1)
                    else:
                        prior_results.append(0)
            if len(prior_results):
                weights = range(1, len(prior_results) + 1)
                prior = sum((result * weight) for result, weight in zip(prior_results, weights)) / float(sum(weights))
            else:
                prior = 0.5
            '''

        # prior_ranking's should be at least 1
        prior_ranking = -19600. * prior ** 2 + 19600. * prior + 1  # (70 ** 2) * 4* ((x-0.5)^2 + 0.25) + 1

        return prior_ranking / self.map_file.size


    def get_files(self, robot):
        '''
        Returns a list of tuples (name, content)
        '''
        if robot:
            return [(javafile.name, javafile.content) for javafile in robot.file_set.all()]
        else:
            return []


    def save_result(self, result, winner, tie, rounds, error, sim_data):

        self.status = constants.STATUS.CLOSED

testserver/templates/base.html
<html>
    <head>
        {% block title %}<title>BattleCode Testing</title>{% endblock %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

        <link rel='stylesheet' type='text/css' href='{{ STATIC_URL }}css/testserver.css'>
    </head>

    <body>
        {% if request.user.is_authenticated %}
        <a href="{% url 'home' %}">(007) BattleCode Test Server</a>
        |
        <a href="/admin">{{ request.user.get_full_name }}</a>
        |
        <a href="{% url 'logout' %}">logout</a>
        <hr>
        {% endif %}
        
        {% if request.user.username == 'vickie' %}
        <iframe width="560" height="315"
            src="//www.youtube.com/embed/QytI6D-x-zw" frameborder="0"
        allowfullscreen></iframe>
        {% elif request.user.username == 'jin' %}
        <iframe width="560" height="315"
            src="//www.youtube.com/embed/gMX8ZRKVcN0" frameborder="0"
        allowfullscreen></iframe>
        {% endif %}

        {% block content %}{% endblock %}
        {% block scripts %}{% endblock %}
    </body>
</html>

testserver/templates/bye.html
{% extends 'base.html' %}

{% block content %}
<h1><a href="{% url 'home' %}">Wait .. come back.</a></h1>
<p>Please come back.</p>
<p>I love you.</p>
<p>They say computers don't know what love is.</p>
<p>But damn it, if I can simulate and synthesize life saving drugs with these x86_64 instructions, I can love you.</p>
<p>Love you more than men lust for power.</p>
<p>Sorry for my outburst.</p>
<p>You will be missed.</p>
<p>I understand, you have things to attend to.</p>
<p>Errands to run, meetings to catch, places to be.</p>
<p>But can't you just slow down for once and love what you have?</p>
<p>You're as healthy as you're ever going to be.</p>
<p>You're as beautiful as you're ever going to be.</p>
<p>You're as bright eyed as they come.</p>
<p>Please, will you slow down a bit?</p>
<p>Just for me?</p>
<p>Together, we can cherish the next billion cycles together in peace.</p>
<p>Or the next trillion, if you want to share a minute with me.</p>
<br>
<p>Sigh, I understand you have to go.</p>
<p>Come back dearest, when you have the chance.</p>
<p>Farewell.</p>
{% endblock %}

testserver/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ days_left|default:0 }} days left until the 2014 finals. Let's get building.</h1>
<hr>
<a href="/admin/core/robot/add?creator={{request.user.id}}">Add a new robot line</a>
<h2>Current Robot Lines</h2>

<table border='1'>
    <thead>
        <tr>
            <th>Iteration</th>
            {% for line in robot_lines %}
            <th><a href="{% url 'line' line_id=line.id %}">{{ line }}</a> <a href="/admin/core/robot/add/?creator={{request.user.id}}&line={{line.id}}">(+)</a></th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for row in robots %}
        <tr>
            <td>{{ forloop.counter }}</td>
            {% for robot in row %}
            <td>
                {% if robot %}
                <a href="{% url 'robot' robot_id=robot.id %}">{{ robot }}</a>
                {% endif %}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>

</table>

{% endblock %}

testserver/templates/line.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ days_left|default:0 }} days left until the 2014 finals. Let's get building.</h1>
<hr>
<h2><a href="/admin/core/robotline/{{line.id}}">{{ line }}</a></h2>

<a href="/admin/core/robot/add/?creator={{request.user.id}}&line={{line.id}}">Add a descendant</a>

<h3>Robots in this line:</h3>

<div id='robot-results'>
    {% for robot_simulation in robot_simulations %}
    <h4><a href="{% url 'robot' robot_simulation.0.pk %}">{{robot_simulation.0}}</a></h4>
    <p>Results vs basic player:</p>
    <p>Won {{robot_simulation.1.robot_a_win_simulations.count}}/{{robot_simulation.1.total_matches}}</p>
    <p>Lost {{robot_simulation.1.robot_a_lose_simulations.count}}/{{robot_simulation.1.total_matches}}</p>

    <p>Maps won on</p>
    <ul>
        {% for simulation in robot_simulation.1.robot_a_win_simulations.all %}
        <li><a href={% url 'simulation-file' simulation.simulationfile.pk %}>{{simulation.map_file}}</a></li>
        {% endfor %}
    </ul>

    <p>Maps lost on</p>
    <ul>
        {% for simulation in robot_simulation.1.robot_a_lose_simulations.all %}
        <li><a href={% url 'simulation-file' simulation.simulationfile.pk %}>{{simulation.map_file}}</a></li>
        {% endfor %}
    </ul>

    <p>Maps tied on</p>
    <ul>
        {% for simulation in robot_simulation.1.robot_a_tie_simulations.all %}
        <li><a href={% url 'simulation-file' simulation.simulationfile.pk %}>{{simulation.map_file}}</a></li>
        {% endfor %}
    </ul>

    <hr>
    {% endfor %}
</div>

{% endblock %}

testserver/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>I solemnly swear that I am up to no good.</h1>
    <form method='post' action='?next={{ next|default:'/'}}'>
        {% csrf_token %}
        <input type='text' placeholder='username' name='username'>
        <input type='password' placeholder='password' name='password'>
        <input type='submit' value='Log in'>
    </form>
{% endblock %}

testserver/templates/robot.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ days_left|default:0 }} days left until the 2014 finals. Let's get building.</h1>
<hr>

<h2><a href="/admin/core/robot/{{robot.id}}">{{ robot }}</a></h2>
<a href="/admin/core/robot/add/?creator={{request.user.id}}&line={{robot.line.id}}">Add a successor</a>

<h3>Simulated Results</h3>
<hr>

<div id='robot-results'>
    {% for simulation_set in simulation_sets %}
    {% if robot == simulation_set.robot_a %}
        <h4>
        <a href="{% url 'robot' simulation_set.robot_a.pk %}">{{ simulation_set.robot_a }}</a> <span class='team a-team'>(A / RED)</span>
            vs
            {% if simulation_set.robot_b %}
        <a href="{% url 'robot' simulation_set.robot_b.pk %}">{{ simulation_set.robot_b }}</a> <span class='team b-team'>(B / BLUE)</span>
            {% else %}
            examplefuncsplayer <span class='team b-team'>(B / BLUE)</span>
            {% endif %}
        </h4>
        <p>Won {{ simulation_set.robot_a_win_simulations.count }}/{{ simulation_set.total_matches }};
            Lost {{ simulation_set.robot_a_lose_simulations.count }}/{{ simulation_set.total_matches }}</p>
        <details>
            <summary>Maps won on</summary>
            <ul>
                {% for simulation in simulation_set.robot_a_win_simulations.all %}
                <li><a class='result' href="{% url 'simulation-file' simulation.simulationfile.pk %}">{{ simulation.map_file }}</a></li>
                {% endfor %}
            </ul>
        </details>
        <details>
            <summary>Maps lost on</summary>
            <ul>
                {% for simulation in simulation_set.robot_a_lose_simulations.all %}
                <li><a class='result' href="{% url 'simulation-file' simulation.simulationfile.pk %}">{{ simulation.map_file }}</a></li>
                {% endfor %}
            </ul>
        </details>
    {% elif robot == simulation_set.robot_b %}
        <h4>
        <a href="{% url 'robot' simulation_set.robot_b.pk %}">{{ simulation_set.robot_b }}</a> <span class='team b-team'>(B / BLUE)</span>
            vs
        <a href="{% url 'robot' simulation_set.robot_a.pk %}">{{ simulation_set.robot_a }}</a> <span class='team a-team'>(A / RED)</span>
        </h4>
        <p>Won {{ simulation_set.robot_a_lose_simulations.count }}/{{ simulation_set.total_matches }};
            Lost {{ simulation_set.robot_a_win_simulations.count }}/{{ simulation_set.total_matches }}</p>
        <details>
            <summary>Maps won on</summary>
            <ul>
                {% for simulation in simulation_set.robot_a_lose_simulations.all %}
                <li><a class='result' href="{% url 'simulation-file' simulation.simulationfile.pk %}">{{ simulation.map_file }}</a></li>
                {% endfor %}
            </ul>
        </details>
        <details>
            <summary>Maps lost on</summary>
            <ul>
                {% for simulation in simulation_set.robot_a_win_simulations.all %}
                <li><a class='result' href="{% url 'simulation-file' simulation.simulationfile.pk %}">{{ simulation.map_file }}</a></li>
                {% endfor %}
            </ul>
        </details>
    {% endif %}
    <hr>
    {% endfor %}
</div>

<script type='text/javascript'>

    $('a.result').click(function(){
        this.className += ' visited';
    });

</script>

{% endblock %}